### GET 
GET http://localhost:3000/api/cards

### POST 
POST http://localhost:3000/api/cards
Content-Type: application/json

{
    "text": "What is CSS?",
    "author": "Jane Doe"
}

### PATCH (update)
PATCH http://localhost:3000/api/cards/6150658c41d0dc56c1a932b0
Content-Type: application/json

{
    "text": "Just changing the title"
}

### DELETE (delete)
DELETE http://localhost:3000/api/cards/6150658c41d0dc56c1a932b0